
import { Plant } from "@/types/plants";

// Sample growable plants data
export const growablePlants: Plant[] = [
  {
    id: 1,
    name: "Basil",
    image: "https://cdn.shopify.com/s/files/1/2016/8569/files/Basil.jpg",
    difficulty: "Easy",
    light: "Full sun",
    water: "Keep soil moist",
    growTime: "3-4 weeks",
    temperature: "65-85°F",
  },
  {
    id: 2,
    name: "Cherry Tomatoes",
    image: "https://www.almanac.com/sites/default/files/styles/or/public/image_nodes/cherry-tomatoes-1.jpg",
    difficulty: "Moderate",
    light: "Full sun",
    water: "Regular watering",
    growTime: "50-75 days",
    temperature: "65-85°F",
  },
  {
    id: 3,
    name: "Mint",
    image: "https://www.almanac.com/sites/default/files/styles/or/public/mint-planting-growing-harvesting.jpg",
    difficulty: "Very Easy",
    light: "Partial shade",
    water: "Keep soil moist",
    growTime: "2-3 weeks",
    temperature: "65-75°F",
  },
  {
    id: 4,
    name: "Lettuce",
    image: "https://www.almanac.com/sites/default/files/styles/or/public/image_nodes/lettuce-hydroponic.jpg",
    difficulty: "Easy",
    light: "Partial sun",
    water: "Regular watering",
    growTime: "45-55 days",
    temperature: "60-70°F",
  },
  {
    id: 5,
    name: "Chili Peppers",
    image: "https://www.almanac.com/sites/default/files/styles/or/public/image_nodes/chili-pepper-hot-spicy-food.jpg",
    difficulty: "Moderate",
    light: "Full sun",
    water: "Moderate watering",
    growTime: "60-90 days",
    temperature: "70-85°F",
  },
  {
    id: 6,
    name: "Cilantro",
    image: "https://www.almanac.com/sites/default/files/styles/or/public/image_nodes/cilantro_coriander.jpg",
    difficulty: "Easy",
    light: "Partial sun",
    water: "Keep soil moist",
    growTime: "3-4 weeks",
    temperature: "65-75°F",
  },
];
